version: "3"
services:
  pdb:
    env_file:
      - db.env
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"

  celery-redis:
    build:
      context: ./redis-docker
      dockerfile: Dockerfile
    container_name: celery-redis
    ports:
      - "6379:6379"

  nimb-app:
    env_file:
      - app.env
    build: .
    ports:
      - "5000:5000"
    init: true
    depends_on:
      - pdb
      - celery-redis
